# Site settings
title: "gjuniioor"
bye_message: "Thx!"
baseurl: "/clyell/"
url: "https://mvigo.github.io/futrue/"
disqus: gjuniioor

# Header settings
nick: "projectfutrue"
mail:
    domain: "https://mvigo.github.io/futrue/"
    ext: "ch"
source_code:
    server: "https://mvigo.github.io/futrue/"
    nick: "gjuniioor"
blog:
    server: "https://mvigo.github.io/futrue/"
    nick: "gjuniioor"
fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
